language: c

script:
 - mkdir build && cd build && rm -rf ./*
 - cmake -DENABLE_COVERAGE_CHECK=ON .. && make
 - mkdir logs && ./bin/demo-xlog > /dev/null
 - ./bin/cov-printer > /dev/null && ./bin/cov-payload > /dev/null
 - ./bin/cov-xlog-no-default-context && ./bin/cov-xlog-no-default-context
 - cd ..

after_success:
 - bash <(curl -s https://codecov.io/bash)
