language: c

script:
 - mkdir build && cd build && rm -rf ./*
 - cmake -DENABLE_COVERAGE_CHECK=ON .. && make
 - mkdir logs && ./bin/demo-xlog > /dev/null
 - ./bin/cov-printer > /dev/null && ./bin/cov-autobuf > /dev/null
 - ./bin/cov-not-default-context && ./bin/cov-not-default-context
 - ./bin/cov-shell && ./bin/cov-plugins > /dev/null
 - cd ..

after_success:
 - bash <(curl -s https://codecov.io/bash)
