language: c

script:
 - mkdir build && cd build && rm -rf ./* && mkdir logs
 - cmake -DENABLE_COVERAGE_CHECK=ON .. && make
 - ./bin/demo-xlog > /dev/null
 - ./bin/cov-printer && ./bin/cov-shell
 - ./bin/cov-not-default-context && ./bin/cov-not-default-context
 - ./bin/cov-autobuf > /dev/null && ./bin/cov-plugins > /dev/null
 - cd ..

after_success:
 - bash <(curl -s https://codecov.io/bash)
